package mocks

import cf "github.com/18F/cf-cdn-service-broker/cf"
import cfclient "github.com/cloudfoundry-community/go-cfclient"
import mock "github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// GetDomainByName provides a mock function with given fields: name
func (_m *Client) GetDomainByName(name string) (cfclient.Domain, error) {
	ret := _m.Called(name)

	var r0 cfclient.Domain
	if rf, ok := ret.Get(0).(func(string) cfclient.Domain); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(cfclient.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrgByGuid provides a mock function with given fields: guid
func (_m *Client) GetOrgByGuid(guid string) (cfclient.Org, error) {
	ret := _m.Called(guid)

	var r0 cfclient.Org
	if rf, ok := ret.Get(0).(func(string) cfclient.Org); ok {
		r0 = rf(guid)
	} else {
		r0 = ret.Get(0).(cfclient.Org)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(guid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

var _ cf.Client = (*Client)(nil)
